dateModified: 1602109293
email:
  fromEmail: $SITE_EMAIL
  fromName: $SITE_NAME
  replyToEmail: null
  template: null
  transportSettings:
    apiKey: $SENDGRID
  transportType: putyourlightson\sendgrid\mail\SendgridAdapter
graphql:
  publicToken:
    enabled: false
    expiryDate: null
plugins:
  cp-field-inspect:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  cp-nav:
    edition: standard
    enabled: true
    schemaVersion: 2.0.7
    settings:
      originalNavHash:
        __assoc__:
          -
            - efb26fec-0e3f-48ee-af83-8cc9cef76dbf
            - W3sibGFiZWwiOiJEYXNoYm9hcmQiLCJ1cmwiOiJkYXNoYm9hcmQiLCJmb250SWNvbiI6ImdhdWdlIn0seyJsYWJlbCI6IkVudHJpZXMiLCJ1cmwiOiJlbnRyaWVzIiwiZm9udEljb24iOiJzZWN0aW9uIn0seyJsYWJlbCI6Ikdsb2JhbHMiLCJ1cmwiOiJnbG9iYWxzIiwiZm9udEljb24iOiJnbG9iZSJ9LHsibGFiZWwiOiJBc3NldHMiLCJ1cmwiOiJhc3NldHMiLCJmb250SWNvbiI6ImFzc2V0cyJ9LHsibGFiZWwiOiJGaWVsZCBNYW5hZ2VyIiwidXJsIjoiZmllbGQtbWFuYWdlciIsImljb24iOiIvVXNlcnMvZGFuaWVsZ29uemFsZXphZGFydmUvRGV2ZWxvcG1lbnQvY3JhZnQtc3RhcnR1cC1raXQvdmVuZG9yL3ZlcmJiL2ZpZWxkLW1hbmFnZXIvc3JjL2ljb24tbWFzay5zdmcifSx7ImxhYmVsIjoiT2xpdmVtZW51cyIsInVybCI6Im9saXZlbWVudXMiLCJpY29uIjoiL1VzZXJzL2RhbmllbGdvbnphbGV6YWRhcnZlL0RldmVsb3BtZW50L2NyYWZ0LXN0YXJ0dXAta2l0L3ZlbmRvci9vbGl2ZXN0dWRpby9jcmFmdC1vbGl2ZW1lbnVzL3NyYy9pY29uLW1hc2suc3ZnIn0seyJsYWJlbCI6IlNFTyIsInVybCI6InNlbyIsImljb24iOiIvVXNlcnMvZGFuaWVsZ29uemFsZXphZGFydmUvRGV2ZWxvcG1lbnQvY3JhZnQtc3RhcnR1cC1raXQvdmVuZG9yL2V0aGVyL3Nlby9zcmMvaWNvbi1tYXNrLnN2ZyIsInN1Ym5hdiI6eyJkYXNoYm9hcmQiOnsibGFiZWwiOiJEYXNoYm9hcmQiLCJ1cmwiOiJzZW8ifSwic2l0ZW1hcCI6eyJsYWJlbCI6IlNpdGVtYXAiLCJ1cmwiOiJzZW8vc2l0ZW1hcCJ9LCJyZWRpcmVjdHMiOnsibGFiZWwiOiJSZWRpcmVjdHMiLCJ1cmwiOiJzZW8vcmVkaXJlY3RzIn0sInNldHRpbmdzIjp7ImxhYmVsIjoiU2V0dGluZ3MiLCJ1cmwiOiJzZW8vc2V0dGluZ3MifX19LHsibGFiZWwiOiJGb3JtcyIsInVybCI6IndoZWVsZm9ybSIsImJhZGdlQ291bnQiOiIwIiwiaWNvbiI6Ii9Vc2Vycy9kYW5pZWxnb256YWxlemFkYXJ2ZS9EZXZlbG9wbWVudC9jcmFmdC1zdGFydHVwLWtpdC92ZW5kb3IveHBlcnRib3QvY3JhZnQtd2hlZWxmb3JtL3NyYy9pY29uLW1hc2suc3ZnIn0seyJ1cmwiOiJ1dGlsaXRpZXMiLCJsYWJlbCI6IlV0aWxpdGllcyIsImZvbnRJY29uIjoidG9vbCIsImJhZGdlQ291bnQiOjB9LHsidXJsIjoic2V0dGluZ3MiLCJsYWJlbCI6IlNldHRpbmdzIiwiZm9udEljb24iOiJzZXR0aW5ncyJ9LHsidXJsIjoicGx1Z2luLXN0b3JlIiwibGFiZWwiOiJQbHVnaW4gU3RvcmUiLCJmb250SWNvbiI6InBsdWdpbiJ9XQ==
  field-manager:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  image-resizer:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  imager:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  minify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  olivemenus:
    edition: standard
    enabled: true
    schemaVersion: 1.1.10
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  redactor-custom-styles:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  retcon:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  sendgrid:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  seo:
    edition: standard
    enabled: true
    schemaVersion: 3.1.1
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 2.2.1
  typedlinkfield:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  wheelform:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
    settings:
      cp_label: Forms
      from_email: $SITE_EMAIL
      from_name: $SITE_NAME
      recaptcha_public: $RECAPTCHA_PUBLIC_KEY
      recaptcha_secret: $RECAPTCHA_PRIVATE_KEY
      recaptcha_version: '3'
      success_message: 'Thank You! we will review your submission shortly.'
      volume_id: ''
system:
  edition: solo
  live: true
  name: $SITE_NAME
  schemaVersion: 3.5.13
  timeZone: Australia/Melbourne
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
