fieldLayouts:
  57d35cc6-d1f9-4d2a-8e1f-f4afe08c9e66:
    tabs:
      -
        elements:
          -
            fieldUid: 0721b120-0247-4c16-8f7e-1ffe8a220f8e
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6078d83c-e8a8-4f84-ab64-49e992715c13
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1b7a3230-f24a-4ac2-a997-3289e43ddf25
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Misc
        sortOrder: 1
handle: site
name: Site
