fieldLayouts:
  57d35cc6-d1f9-4d2a-8e1f-f4afe08c9e66:
    tabs:
      -
        fields:
          1b7a3230-f24a-4ac2-a997-3289e43ddf25:
            required: false
            sortOrder: 1
        name: Misc
        sortOrder: 1
handle: site
name: Site
